### PR TITLE
Implement local testing (#13)

### PR DESCRIPTION
**Pull request by ChristopherMacGown**

### CODE REVIEW

**Comment by ilianaw** [comment]
I feel like I should just be able to run `make test` and Make should compile the examples before running the test commands. Is that an improvement you'd like to write?

**Comment by ChristopherMacGown** [comment]
Yep, I can do that. It will probably take a Makefile in each example directory to make the recursive build work properly. Is that ok?

**Comment by ilianaw** [comment]
Hm. Would `cd examples/echo; cargo build --release` work too?

If all that's happening is execing cargo in a directory I'm not particularly thrilled about there being a Makefile there too (especially since the example dirs are designed as much as possible to be cargo culted to new projects).

**Comment by ChristopherMacGown** [comment]
I've moved the Makefile out of the root of the repo into `test/` and split it up into two sub-Makefiles `Makefile.local` and `Makefile.docker`. The `.local` version allows you to build and test the examples locally, and the `.docker` version builds them via the docker builder and tests them against `amazonlinux:latest`.

I also added a commit that removes the `PYENV` references from `builder/build.sh` because that fails as well due to the unbound variable.

**Comment by ilianaw** [comment]
> I also added a commit that removes the PYENV references from builder/build.sh because that fails as well due to the unbound variable.

oh whoops. :(

I'll hopefully be able to test and merge this tonight.

**Comment by ChristopherMacGown** [comment]
No worries, I dropped the conflicting commit.

**Pull request merged**
